AllCops:
  Exclude:
    - "hoolp-client.gemspec"
  TargetRubyVersion: 2.3

Style/StringLiterals:
  EnforcedStyle: double_quotes
Style/Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Metrics/LineLength:
  Enabled: false
Metrics/MethodLength:
  Max: 181
